import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import {
  NEIGHBORHOODS,
  YEARS,
  EVIDENCE,
  getNeighborhoodById,
  calcChange,
} from './data/bengaluru.js';
import { generateChangeStory, ChangeStoryError } from './groq.js';

// Metrics sent to the AI investigator, mirroring the "Key indicators" rows shown in the UI.
const METRICS = [
  { key: 'builtUp', label: 'Built-up area', unit: '%' },
  { key: 'greenSpace', label: 'Green space', unit: '%' },
  { key: 'commercialArea', label: 'Commercial area', unit: '%' },
  { key: 'roadDensity', label: 'Road density', unit: ' km/km²' },
  { key: 'transitStations', label: 'Transit stations', unit: '' },
];

function computeChanges(neighborhood, fromYear, toYear) {
  return METRICS.map((m) => {
    const fromValue = neighborhood.data[fromYear][m.key];
    const toValue = neighborhood.data[toYear][m.key];
    const delta = calcChange(neighborhood, fromYear, toYear, m.key);
    const change = m.key === 'transitStations' ? `${delta >= 0 ? '+' : ''}${delta}` : `${delta >= 0 ? '+' : ''}${delta}%`;
    return { label: m.label, unit: m.unit, fromValue, toValue, change };
  });
}

const ERROR_STATUS = {
  MISSING_API_KEY: 500,
  TIMEOUT: 504,
  PROVIDER_ERROR: 502,
  INVALID_RESPONSE: 502,
};

const ERROR_MESSAGE = {
  MISSING_API_KEY: 'The AI investigator is not configured on this server. Contact the site administrator.',
  TIMEOUT: 'The AI investigation timed out. Please try again.',
  PROVIDER_ERROR: 'The AI service failed to respond. Please try again.',
  INVALID_RESPONSE: 'The AI service returned an unexpected response. Please try again.',
};

const app = express();
const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());

// GET /api/neighborhoods — full prepared dataset used by City Explorer and Neighborhood pages.
app.get('/api/neighborhoods', (_req, res) => {
  res.json({ years: YEARS, neighborhoods: NEIGHBORHOODS, isDemoData: true });
});

// GET /api/neighborhoods/:id — single neighborhood.
app.get('/api/neighborhoods/:id', (req, res) => {
  const neighborhood = getNeighborhoodById(req.params.id);
  if (!neighborhood) {
    return res.status(404).json({ error: 'Neighborhood not found' });
  }
  res.json({ years: YEARS, neighborhood, isDemoData: true });
});

// POST /api/change-story — City Change Investigator, backed by a real Groq call.
// See skills/ai-change-story/SKILL.md. Groq receives only the neighborhood, the
// exact selected year range, the computed observed changes for that range, and our
// own evidence list — never asked to invent facts, stats, evidence, or a different
// year range. Evidence returned to the client is always ours, never the model's.
app.post('/api/change-story', async (req, res) => {
  const { neighborhoodId, fromYear, toYear } = req.body || {};

  const neighborhood = getNeighborhoodById(neighborhoodId);
  if (!neighborhood) {
    return res.status(404).json({ error: 'Unknown neighborhood' });
  }
  if (!YEARS.includes(fromYear) || !YEARS.includes(toYear) || fromYear >= toYear) {
    return res.status(400).json({ error: 'fromYear must be an earlier valid year than toYear' });
  }

  const evidence = EVIDENCE[neighborhoodId] || [];
  const changes = computeChanges(neighborhood, fromYear, toYear);

  try {
    const result = await generateChangeStory({ neighborhood, fromYear, toYear, changes, evidence });

    res.json({
      source: 'live-ai',
      neighborhoodId,
      fromYear,
      toYear,
      whatChanged: result.whatChanged,
      whyItHappened: result.possibleReasons,
      interpretation: result.causationAssessment,
      evidence,
      disclaimer:
        'This explanation was generated by Groq from the demo dataset and evidence list above only, and may not reflect verified real-world causation.',
    });
  } catch (err) {
    const code = err instanceof ChangeStoryError ? err.code : 'PROVIDER_ERROR';
    console.error(`[change-story] ${code}: ${err.message}`);
    res.status(ERROR_STATUS[code] || 502).json({ error: ERROR_MESSAGE[code] || ERROR_MESSAGE.PROVIDER_ERROR });
  }
});

app.listen(PORT, () => {
  console.log(`Memory of a City API listening on http://localhost:${PORT}`);
});
